package dailybread

import (
	"bytes"
	"crypto/tls"
	"fmt"
	"net/smtp"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/joho/godotenv"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"

	"solomon-cron/internal/logger"
)

type Service struct {
	logger    *logger.Logger
	assetsDir string // base directory for assets (prompts, templates, and history logs)
}

func New(l *logger.Logger, assetsDir string) *Service {
	return &Service{
		logger:    l,
		assetsDir: assetsDir,
	}
}

func (s *Service) Run(templateName string) error {
	// Load environment variables
	_ = godotenv.Load()

	s.logger.Log("[daily-bread] Starting devotional newsletter generation...")

	dateDisplay := getFormattedDate()
	todayISO := time.Now().Format("2006-01-02")

	promptFile := filepath.Join(s.assetsDir, "prompts", fmt.Sprintf("%s.md", templateName))
	templateFile := filepath.Join(s.assetsDir, "templates", "template.html")

	// 1. Execute Copilot CLI
	markdownContent, err := s.executeCopilot(promptFile)
	if err != nil {
		return fmt.Errorf("copilot execution failed: %w", err)
	}

	// 2. Compile HTML
	htmlContent, err := s.compileNewsletter(markdownContent, templateFile, dateDisplay)
	if err != nil {
		return fmt.Errorf("newsletter compilation failed: %w", err)
	}

	// 3. Save history to assets/logs/html/YYYY-MM-DD.html
	_, err = s.saveHistoryLog(htmlContent, todayISO)
	if err != nil {
		s.logger.Log("[daily-bread] Warning: Failed to save HTML history log: %v", err)
	}

	// 4. Send SMTP Email
	err = s.sendEmail(htmlContent)
	if err != nil {
		return fmt.Errorf("email dispatch failed: %w", err)
	}

	s.logger.Log("[daily-bread] Devotional newsletter successfully sent to recipient!")
	return nil
}

func getFormattedDate() string {
	months := map[time.Month]string{
		time.January:   "Janeiro",
		time.February:  "Fevereiro",
		time.March:     "Março",
		time.April:     "Abril",
		time.May:       "Maio",
		time.June:      "Junho",
		time.July:      "Julho",
		time.August:    "Agosto",
		time.September: "Setembro",
		time.October:   "Outubro",
		time.November:  "Novembro",
		time.December:  "Dezembro",
	}
	now := time.Now()
	return fmt.Sprintf("%d de %s de %d", now.Day(), months[now.Month()], now.Year())
}

func (s *Service) executeCopilot(promptPath string) (string, error) {
	if _, err := os.Stat(promptPath); os.IsNotExist(err) {
		return "", fmt.Errorf("prompt file not found at: %s", promptPath)
	}

	s.logger.Log("[daily-bread] Reading prompt from: %s", promptPath)
	promptBytes, err := os.ReadFile(promptPath)
	if err != nil {
		return "", fmt.Errorf("failed to read prompt file: %w", err)
	}
	promptContent := strings.TrimSpace(string(promptBytes))

	if filepath.Base(promptPath) != "_base.md" {
		basePromptPath := filepath.Join(filepath.Dir(promptPath), "_base.md")
		if _, err := os.Stat(basePromptPath); err == nil {
			s.logger.Log("[daily-bread] Merging with base prompt from: %s", basePromptPath)
			baseBytes, err := os.ReadFile(basePromptPath)
			if err == nil {
				baseContent := strings.TrimSpace(string(baseBytes))
				if baseContent != "" {
					promptContent = baseContent + "\n\n" + promptContent
				}
			} else {
				s.logger.Log("[daily-bread] Warning: Failed to read base prompt: %v", err)
			}
		}
	}

	s.logger.Log("[daily-bread] Dispatching prompt content to GitHub Copilot CLI...")
	
	// Execute copilot CLI
	cmd := exec.Command("copilot", "-s", "-p", promptContent, "--no-ask-user", "--yolo")
	
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	
	err = cmd.Run()
	if err != nil {
		return "", fmt.Errorf("copilot CLI execution error: %v\nStderr: %s\nStdout: %s", err, stderr.String(), stdout.String())
	}
	
	outputText := strings.TrimSpace(stdout.String())
	if outputText == "" {
		return "", fmt.Errorf("copilot CLI returned an empty response")
	}
	
	s.logger.Log("[daily-bread] Content successfully generated by Copilot CLI!")
	return outputText, nil
}

func (s *Service) compileNewsletter(contentMarkdown, templatePath, dateDisplay string) (string, error) {
	if _, err := os.Stat(templatePath); os.IsNotExist(err) {
		return "", fmt.Errorf("template file not found at: %s", templatePath)
	}

	s.logger.Log("[daily-bread] Converting generated Markdown reflections to HTML...")
	
	// Configure Goldmark parser with GFM features (such as tables)
	md := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
		),
	)
	
	var buf bytes.Buffer
	if err := md.Convert([]byte(contentMarkdown), &buf); err != nil {
		return "", fmt.Errorf("failed to convert markdown to html: %w", err)
	}
	contentHTML := buf.String()

	s.logger.Log("[daily-bread] Loading HTML layout template from: %s", templatePath)
	templateBytes, err := os.ReadFile(templatePath)
	if err != nil {
		return "", fmt.Errorf("failed to read HTML template: %w", err)
	}
	templateHTML := string(templateBytes)

	// Inject placeholders
	compiledHTML := strings.ReplaceAll(templateHTML, "{{date}}", dateDisplay)
	compiledHTML = strings.ReplaceAll(compiledHTML, "{{content}}", contentHTML)

	return compiledHTML, nil
}

func (s *Service) saveHistoryLog(htmlContent, dateStr string) (string, error) {
	historyDir := filepath.Join(s.assetsDir, "logs", "html")
	err := os.MkdirAll(historyDir, 0755)
	if err != nil {
		return "", fmt.Errorf("failed to create directory %s: %w", historyDir, err)
	}
	
	logFile := filepath.Join(historyDir, fmt.Sprintf("%s.html", dateStr))
	err = os.WriteFile(logFile, []byte(htmlContent), 0644)
	if err != nil {
		return "", fmt.Errorf("failed to write HTML log file: %w", err)
	}
	
	s.logger.Log("[daily-bread] Local HTML history saved at: %s", logFile)
	return logFile, nil
}

func (s *Service) sendEmail(htmlContent string) error {
	s.logger.Log("[daily-bread] Connecting to SMTP server to dispatch newsletter...")
	
	host := os.Getenv("SMTP_HOST")
	portStr := os.Getenv("SMTP_PORT")
	user := os.Getenv("SMTP_USER")
	pass := os.Getenv("SMTP_PASSWORD")
	useTLS := strings.ToLower(os.Getenv("SMTP_USE_TLS")) != "false"

	emailFrom := os.Getenv("EMAIL_FROM")
	if emailFrom == "" {
		emailFrom = fmt.Sprintf("Pão Diário <%s>", user)
	}
	emailTo := os.Getenv("EMAIL_TO")
	emailSubject := os.Getenv("EMAIL_SUBJECT")
	if emailSubject == "" {
		emailSubject = "Pão Diário - Edição de Hoje"
	}

	if host == "" || portStr == "" || user == "" || pass == "" || emailTo == "" {
		return fmt.Errorf("SMTP configuration fields or EMAIL_TO are empty in environment")
	}

	// Build MIME message
	header := make(map[string]string)
	header["From"] = emailFrom
	header["To"] = emailTo
	header["Subject"] = emailSubject
	header["MIME-Version"] = "1.0"
	header["Content-Type"] = `text/html; charset="utf-8"`

	var msg bytes.Buffer
	for k, v := range header {
		msg.WriteString(fmt.Sprintf("%s: %s\r\n", k, v))
	}
	msg.WriteString("\r\n")
	msg.WriteString(htmlContent)

	addr := host + ":" + portStr
	auth := smtp.PlainAuth("", user, pass, host)

	s.logger.Log("[daily-bread] Connecting to: %s", addr)
	
	if portStr == "465" {
		// SSL/TLS Direct Connection
		tlsconfig := &tls.Config{
			InsecureSkipVerify: false,
			ServerName:         host,
		}
		
		conn, err := tls.Dial("tcp", addr, tlsconfig)
		if err != nil {
			return fmt.Errorf("failed SSL/TLS connection dial: %w", err)
		}
		defer conn.Close()

		client, err := smtp.NewClient(conn, host)
		if err != nil {
			return fmt.Errorf("failed SMTP client instantiation: %w", err)
		}
		defer client.Close()

		if err = client.Auth(auth); err != nil {
			return fmt.Errorf("failed SMTP authentication: %w", err)
		}

		if err = client.Mail(user); err != nil {
			return fmt.Errorf("failed SMTP MAIL FROM envelope: %w", err)
		}

		if err = client.Rcpt(emailTo); err != nil {
			return fmt.Errorf("failed SMTP RCPT TO envelope: %w", err)
		}

		w, err := client.Data()
		if err != nil {
			return fmt.Errorf("failed SMTP DATA stream start: %w", err)
		}

		_, err = w.Write(msg.Bytes())
		if err != nil {
			return fmt.Errorf("failed to write SMTP payload: %w", err)
		}

		err = w.Close()
		if err != nil {
			return fmt.Errorf("failed to close SMTP stream: %w", err)
		}

		s.logger.Log("[daily-bread] Securing and completing transaction with SMTP server...")
		return client.Quit()
	} else {
		// STARTTLS Standard Connection (Port 587)
		if useTLS {
			s.logger.Log("[daily-bread] Securing connection with STARTTLS handshake...")
		}
		s.logger.Log("[daily-bread] Delivering payload via standard SendMail...")
		
		err := smtp.SendMail(addr, auth, user, []string{emailTo}, msg.Bytes())
		if err != nil {
			return fmt.Errorf("failed SendMail call: %w", err)
		}
		return nil
	}
}
