package dailybread

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/joho/godotenv"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"

	"solomon-cron/internal/ai"
	"solomon-cron/internal/logger"
	"solomon-cron/internal/mailer"
)

type Service struct {
	logger    *logger.Logger
	assetsDir string // base directory for assets (prompts, templates, and history logs)
}

func New(l *logger.Logger, assetsDir string) *Service {
	return &Service{
		logger:    l,
		assetsDir: assetsDir,
	}
}

func (s *Service) Run(templateName string) error {
	// Load environment variables
	_ = godotenv.Load()

	s.logger.Log("[daily-bread] Starting devotional newsletter generation...")

	dateDisplay := getFormattedDate()

	promptFile := filepath.Join(s.assetsDir, "prompts", fmt.Sprintf("%s.md", templateName))
	templateFile := filepath.Join(s.assetsDir, "templates", "template.html")

	// 1. Initialize AI Provider
	aiProvider, err := ai.NewProvider()
	if err != nil {
		return fmt.Errorf("failed to initialize AI provider: %w", err)
	}

	// 2. Execute AI Provider
	markdownContent, err := s.executeAI(aiProvider, promptFile)
	if err != nil {
		return fmt.Errorf("AI execution failed: %w", err)
	}

	// 3. Compile HTML
	htmlContent, err := s.compileNewsletter(markdownContent, templateFile, dateDisplay)
	if err != nil {
		return fmt.Errorf("newsletter compilation failed: %w", err)
	}

	// 3. Send SMTP Email
	err = s.sendEmail(htmlContent, templateName)
	if err != nil {
		return fmt.Errorf("email dispatch failed: %w", err)
	}

	s.logger.Log("[daily-bread] Devotional newsletter successfully sent to recipient!")
	return nil
}

func getFormattedDate() string {
	months := map[time.Month]string{
		time.January:   "Janeiro",
		time.February:  "Fevereiro",
		time.March:     "Março",
		time.April:     "Abril",
		time.May:       "Maio",
		time.June:      "Junho",
		time.July:      "Julho",
		time.August:    "Agosto",
		time.September: "Setembro",
		time.October:   "Outubro",
		time.November:  "Novembro",
		time.December:  "Dezembro",
	}
	now := time.Now()
	return fmt.Sprintf("%d de %s de %d", now.Day(), months[now.Month()], now.Year())
}

func (s *Service) executeAI(p ai.Provider, promptPath string) (string, error) {
	if _, err := os.Stat(promptPath); os.IsNotExist(err) {
		return "", fmt.Errorf("prompt file not found at: %s", promptPath)
	}

	s.logger.Log("[daily-bread] Reading prompt from: %s", promptPath)
	promptBytes, err := os.ReadFile(promptPath)
	if err != nil {
		return "", fmt.Errorf("failed to read prompt file: %w", err)
	}
	promptContent := strings.TrimSpace(string(promptBytes))

	if filepath.Base(promptPath) != "_base.md" {
		basePromptPath := filepath.Join(filepath.Dir(promptPath), "_base.md")
		if _, err := os.Stat(basePromptPath); err == nil {
			s.logger.Log("[daily-bread] Merging with base prompt from: %s", basePromptPath)
			baseBytes, err := os.ReadFile(basePromptPath)
			if err == nil {
				baseContent := strings.TrimSpace(string(baseBytes))
				if baseContent != "" {
					promptContent = baseContent + "\n\n" + promptContent
				}
			} else {
				s.logger.Log("[daily-bread] Warning: Failed to read base prompt: %v", err)
			}
		}
	}

	s.logger.Log("[daily-bread] Dispatching prompt content to AI provider...")
	
	outputText, err := p.Generate(promptContent)
	if err != nil {
		return "", err
	}
	
	s.logger.Log("[daily-bread] Content successfully generated by AI provider!")
	return outputText, nil
}

func (s *Service) compileNewsletter(contentMarkdown, templatePath, dateDisplay string) (string, error) {
	if _, err := os.Stat(templatePath); os.IsNotExist(err) {
		return "", fmt.Errorf("template file not found at: %s", templatePath)
	}

	s.logger.Log("[daily-bread] Converting generated Markdown reflections to HTML...")
	
	// Configure Goldmark parser with GFM features (such as tables)
	md := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
		),
	)
	
	var buf bytes.Buffer
	if err := md.Convert([]byte(contentMarkdown), &buf); err != nil {
		return "", fmt.Errorf("failed to convert markdown to html: %w", err)
	}
	contentHTML := buf.String()

	s.logger.Log("[daily-bread] Loading HTML layout template from: %s", templatePath)
	templateBytes, err := os.ReadFile(templatePath)
	if err != nil {
		return "", fmt.Errorf("failed to read HTML template: %w", err)
	}
	templateHTML := string(templateBytes)

	// Inject placeholders
	compiledHTML := strings.ReplaceAll(templateHTML, "{{date}}", dateDisplay)
	compiledHTML = strings.ReplaceAll(compiledHTML, "{{content}}", contentHTML)

	return compiledHTML, nil
}

func (s *Service) sendEmail(htmlContent, templateName string) error {
	s.logger.Log("[daily-bread] Preparing to dispatch newsletter via generic mailer...")

	m := mailer.New(mailer.ConfigFromEnv())

	emailFrom := os.Getenv("EMAIL_FROM")
	if emailFrom == "" {
		emailFrom = fmt.Sprintf("Pão Diário <%s>", os.Getenv("SMTP_USER"))
	}

	emailSubject := os.Getenv("EMAIL_SUBJECT")
	if emailSubject == "" {
		emailSubject = fmt.Sprintf("Pão Diário - %s", cases.Title(language.Und).String(templateName))
	}

	err := m.Send(mailer.Message{
		From:    emailFrom,
		To:      os.Getenv("EMAIL_TO"),
		Subject: emailSubject,
		Body:    htmlContent,
	})

	if err != nil {
		return fmt.Errorf("mailer error: %w", err)
	}

	s.logger.Log("[daily-bread] Email successfully delivered by the generic mailer!")
	return nil
}
